server:
  port:  8005
spring:
  cloud:
    nacos:
      discovery:
        server-addr:  127.0.01:8848
    gateway:
      routes:
         - id: NacosProvider
           uri: lb://NacosProvider
           predicates:
                - Path=/provider/**
  application:
    name: NacosGateway



